name: SwiftLint

on:
  pull_request:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: "5.7"
      - name: Run SwiftLint (Only files changed in the pull reuqest)
        uses: sinoru/actions-swiftlint@v6
        env:
          DIFF_BASE: ${{ github.base_ref }}
